<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>default</LangVersion>
        <Nullable>enable</Nullable>
        <RootNamespace>RuniOS.APIBridge.UnityEngine</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RuniOS.APIBridge\RuniOS.APIBridge.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="UnityEngine.CoreModule" Publicize="true">
          <HintPath>..\dlls\UnityEngine.CoreModule.dll</HintPath>
        </Reference>
        <Reference Include="UnityEngine.IMGUIModule" Publicize="true">
            <HintPath>..\dlls\UnityEngine.IMGUIModule.dll</HintPath>
        </Reference>
    </ItemGroup>

</Project>
