using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RuniOS.APIBridge
{
    public partial class BridgeGeneratorBuilder
    {
        public static string Build(INamedTypeSymbol targetSymbol, out IReadOnlyList<INamedTypeSymbol> nonPublicTypeSymbols, int tabSpaceCount = 4) => new BridgeGeneratorBuilder(targetSymbol, tabSpaceCount).Build(out nonPublicTypeSymbols);
        
        readonly INamedTypeSymbol targetSymbol;
        readonly int tabSpaceCount;
        
        readonly StringBuilder builder = new StringBuilder();
        bool isFirstAppend = false;
        int tabCount = 0;
        
        readonly List<INamedTypeSymbol> nonPublicTypeSymbols = [];
        
        BridgeGeneratorBuilder(INamedTypeSymbol targetSymbol, int tabSpaceCount = 4)
        {
            this.targetSymbol = targetSymbol;
            this.tabSpaceCount = tabSpaceCount;
        }

        void Append(string text = "")
        {
            if (!isFirstAppend)
            {
                for (int i = 0; i < tabCount * tabSpaceCount; i++)
                    builder.Append(' ');
            }
            
            builder.Append(text);
            isFirstAppend = true;
        }
        
        void AppendLine(string text = "")
        {
            if (!isFirstAppend)
            {
                for (int i = 0; i < tabCount * tabSpaceCount; i++)
                    builder.Append(' ');
            }
            
            builder.AppendLine(text);
            isFirstAppend = false;
        }
        
        void StartBlock()
        {
            AppendLine("{");
            tabCount++;
        }
        
        void EndBlock()
        {
            tabCount--;
            AppendLine("}");
        }
        
        void StartComment() => AppendLine("/*");

        void EndComment() => AppendLine("/*");

        void AppendLineDocumentation(ISymbol symbol)
        {
            string? comment = symbol.GetDocumentationCommentXml();
            if (comment != null)
                AppendLine(comment);
        }
        
        public string Build(out IReadOnlyList<INamedTypeSymbol> nonPublicTypeSymbols)
        {
            try
            {
                builder.Clear();
                isFirstAppend = false;
                tabCount = 0;

                this.nonPublicTypeSymbols.Clear();
                nonPublicTypeSymbols = this.nonPublicTypeSymbols.AsReadOnly();

                AppendLine("// <auto-generated/>");
                AppendLine("#nullable enable");
                AppendLine($"namespace {targetSymbol.GetBridgeNamespace()}");
                StartBlock();

                IEnumerable<INamedTypeSymbol> containingTypes = targetSymbol.GetContainingTypes();
                foreach (var containingType in containingTypes.Reverse())
                {
                    if (containingType.IsObsolete(out string message) && SymbolEqualityComparer.Default.Equals(containingType, containingTypes.Last()))
                        AppendLine($"[System.ObsoleteAttribute({message})]");
                    AppendLine(containingType.GetTypeDeclarationText());
                    StartBlock();
                }

                switch (targetSymbol.TypeKind)
                {
                    case TypeKind.Class:
                    {
                        ClassBuilder.Build(this, targetSymbol);
                        break;
                    }
                    case TypeKind.Interface:
                    {
                        InterfaceBuilder.Build(this, targetSymbol);
                        break;
                    }
                    case TypeKind.Enum:
                    {
                        EnumBuilder.Build(this, targetSymbol);
                        break;
                    }
                    case TypeKind.Struct:
                    {
                        StructBuilder.Build(this, targetSymbol);
                        break;
                    }
                }

                foreach (var _ in containingTypes)
                    EndBlock();

                EndBlock();
                return builder.ToString();
            }
            catch (Exception e)
            {
                throw new Exception($"{targetSymbol} 타입에서 예외    {e.StackTrace}    {e}");
            }
        }
    }
}