using System.Linq;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Threading;

namespace RuniOS.APIBridge
{
    /// <summary>
    /// 어셈블리 수준의 GenerateAPIBridgeFor 어트리뷰트를 기반으로 브릿지 코드를 생성하는 소스 생성기입니다.
    /// </summary>
    [Generator]
    public class BridgeGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// 소스 생성기를 초기화하고 코드 생성 로직을 등록합니다.
        /// </summary>
        /// <param name="context">증분 생성기 초기화 컨텍스트입니다.</param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // #1. 생성기에 필요한 사용자 정의 속성을 생성합니다.
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource(
                    "GenerateAPIBridgeForAttribute.g.cs",
                    """
                    // <auto-generated/>
                    using System;
                    namespace RuniOS.APIBridge
                    {
                        /// <summary>
                        /// 이 어트리뷰트가 적용된 어셈블리에 대해 지정된 타입의 브릿지 코드를 생성하도록 지시합니다.
                        /// </summary>
                        [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
                        public sealed class GenerateAPIBridgeFor(params Type[] types) : Attribute
                        {
                            /// <summary>
                            /// 브릿지 코드를 생성할 대상 타입들입니다.
                            /// </summary>
                            public Type[] types { get; set; } = types;
                        }
                    }
                    """);
            });

            // 1. 어셈블리 수준의 GenerateAPIBridgeFor 어트리뷰트를 모두 찾아 모든 타입 인자를 추출합니다.
            var targetTypesProvider = context.SyntaxProvider
                .CreateSyntaxProvider
                (
                    // predicate: 컴파일 단위 구문(CompilationUnitSyntax)을 찾습니다.
                    static (SyntaxNode s, CancellationToken _) => s is CompilationUnitSyntax,
                    // transform: 어셈블리 어트리뷰트를 포함하는 CompilationUnitSyntax를 SemanticModel과 함께 추출하고 타입 정보를 반환합니다.
                    static (GeneratorSyntaxContext ctx, CancellationToken _) =>
                    {
                        CompilationUnitSyntax compilationUnit = (CompilationUnitSyntax)ctx.Node;

                        // "RuniOS.APIBridge.GenerateAPIBridgeFor" 어트리뷰트를 모두 찾습니다.
                        IEnumerable<AttributeSyntax> assemblyAttributes = compilationUnit.AttributeLists
                            .SelectMany(static al => al.Attributes)
                            .Where(a =>
                            {
                                var symbol = ctx.SemanticModel.GetSymbolInfo(a).Symbol as IMethodSymbol;
                                // 네임스페이스와 어트리뷰트 이름을 정확히 비교합니다.
                                return symbol?.ContainingType.ToDisplayString() == "RuniOS.APIBridge.GenerateAPIBridgeFor";
                            });

                        if (!assemblyAttributes.Any())
                            return ImmutableArray<INamedTypeSymbol>.Empty;

                        ImmutableArray<INamedTypeSymbol>.Builder types = ImmutableArray.CreateBuilder<INamedTypeSymbol>();
                        foreach (var attribute in assemblyAttributes)
                        {
                            if (attribute.ArgumentList?.Arguments is not { } arguments)
                                continue;

                            foreach (AttributeArgumentSyntax argument in arguments)
                            {
                                if (argument.Expression is not TypeOfExpressionSyntax typeOfExpression)
                                    continue;

                                SymbolInfo typeInfo = ctx.SemanticModel.GetSymbolInfo(typeOfExpression.Type);
                                if (typeInfo.Symbol is not INamedTypeSymbol typeSymbol)
                                    continue;

                                types.Add(typeSymbol);
                            }
                        }

                        return types.ToImmutable();
                    }
                )
                .Where(static s => !s.IsEmpty) // 비어있지 않은 결과만 필터링합니다.
                .SelectMany(static (types, _) => types) // 타입 목록을 단일 스트림으로 평탄화합니다.
                .Collect(); // 모든 결과를 수집합니다.

            // 2. 수집된 모든 타입에 대해 브릿지 코드를 생성합니다.
            context.RegisterSourceOutput(targetTypesProvider, static (SourceProductionContext spc, ImmutableArray<INamedTypeSymbol> targetSymbols) =>
            {
                IEnumerable<INamedTypeSymbol> distinctTargets = targetSymbols.Select(static x => x.OriginalDefinition).Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>();
                if (!distinctTargets.Any())
                    return;
                
                List<INamedTypeSymbol> bridgedNonPublicTypeSymbols = [];
                List<INamedTypeSymbol> nonPublicTypeSymbols = [];
                foreach (var targetSymbol in distinctTargets)
                    Build(targetSymbol);
                
                nonPublicTypeSymbols = nonPublicTypeSymbols.Select(static x => x.OriginalDefinition).Except<INamedTypeSymbol>(bridgedNonPublicTypeSymbols, SymbolEqualityComparer.Default).ToList();

                {
                    while (nonPublicTypeSymbols.Any())
                    {
                        foreach (INamedTypeSymbol? targetSymbol in nonPublicTypeSymbols.ToArray())
                        {
                            bridgedNonPublicTypeSymbols.Add(targetSymbol);
                            Build(targetSymbol);
                        }
                        
                        nonPublicTypeSymbols = nonPublicTypeSymbols.Select(static x => x.OriginalDefinition).Except<INamedTypeSymbol>(bridgedNonPublicTypeSymbols, SymbolEqualityComparer.Default).ToList();
                    }
                }
                
                return;

                void Build(INamedTypeSymbol targetSymbol)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(new DiagnosticDescriptor("LOG001", "LOG", targetSymbol.Name, "LOG", DiagnosticSeverity.Info, true), Location.None));
                    bridgedNonPublicTypeSymbols.Add(targetSymbol);
                    
                    string fileName = $"{targetSymbol.GetBridgeNamespace()}.{GetBridgeTypeNameIncludeContaining(targetSymbol)}";
                    fileName += ".g.cs";

                    spc.AddSource(fileName, BridgeGeneratorBuilder.Build(targetSymbol, out IReadOnlyList<INamedTypeSymbol> result));
                    nonPublicTypeSymbols.AddRange(result);
                    return;

                    static string GetBridgeTypeNameIncludeContaining(INamedTypeSymbol symbol)
                    {
                        string result = string.Empty;
                        if (symbol.ContainingType != null)
                            result += GetBridgeTypeNameIncludeContaining(symbol.ContainingType) + '.';

                        result += symbol.GetBridgeTypeName();
                        if (symbol.TypeParameters.Any())
                            result += "`" + symbol.TypeParameters.Length;
                        
                        return result;
                    }
                }
            });
        }
    }
}
