using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace RuniOS.APIBridge
{
    public partial class BridgeGeneratorBuilder
    {
        public static string Build(ImmutableArray<string> targetAssemblies, INamedTypeSymbol targetSymbol, ImmutableArray<string> includeMembers, ImmutableArray<string> excludeMembers, bool forceStatic, bool skipCreateInstance, out IReadOnlyList<BridgeGenerationData> nonPublicTypeSymbols, int tabSpaceCount = 4) => new BridgeGeneratorBuilder(targetAssemblies, targetSymbol, includeMembers, excludeMembers, forceStatic, skipCreateInstance, tabSpaceCount).Build(out nonPublicTypeSymbols);
        
        readonly ImmutableArray<string> targetAssemblies;
        readonly INamedTypeSymbol targetSymbol;
        readonly ImmutableArray<string> includeMembers;
        readonly ImmutableArray<string> excludeMembers;
        readonly bool forceStatic;
        readonly bool skipCreateInstance;
        readonly int tabSpaceCount;
        
        readonly StringBuilder builder = new StringBuilder();
        bool isFirstAppend = false;
        int tabCount = 0;
        
        readonly List<BridgeGenerationData> nonPublicTypeSymbols = [];
        
        BridgeGeneratorBuilder(ImmutableArray<string> targetAssemblies, INamedTypeSymbol targetSymbol, ImmutableArray<string> includeMembers, ImmutableArray<string> excludeMembers, bool forceStatic, bool skipCreateInstance, int tabSpaceCount = 4)
        {
            this.targetAssemblies = targetAssemblies;
            this.targetSymbol = targetSymbol;
            this.includeMembers = includeMembers;
            this.excludeMembers = excludeMembers;
            this.forceStatic = forceStatic;
            this.skipCreateInstance = skipCreateInstance;
            this.tabSpaceCount = tabSpaceCount;
        }

        void Append(string text = "")
        {
            if (!isFirstAppend)
            {
                for (int i = 0; i < tabCount * tabSpaceCount; i++)
                    builder.Append(' ');
            }
            
            builder.Append(text);
            isFirstAppend = true;
        }
        
        void AppendLine(string text = "")
        {
            if (!isFirstAppend)
            {
                for (int i = 0; i < tabCount * tabSpaceCount; i++)
                    builder.Append(' ');
            }
            
            builder.AppendLine(text);
            isFirstAppend = false;
        }
        
        void StartBlock()
        {
            AppendLine("{");
            tabCount++;
        }
        
        void EndBlock()
        {
            tabCount--;
            AppendLine("}");
        }
        
        void StartComment() => AppendLine("/*");

        void EndComment() => AppendLine("*/");

        void AppendLineDocumentation(ISymbol symbol)
        {
            string? comment = symbol.GetDocumentationCommentXml();
            if (comment != null)
                AppendLine(comment);
        }
        
        public string Build(out IReadOnlyList<BridgeGenerationData> nonPublicTypeSymbols)
        {
            try
            {
                builder.Clear();
                isFirstAppend = false;
                tabCount = 0;

                this.nonPublicTypeSymbols.Clear();
                nonPublicTypeSymbols = this.nonPublicTypeSymbols.AsReadOnly();

                AppendLine("// <auto-generated/>");
                AppendLine("#nullable enable");
                AppendLine($"namespace {targetSymbol.GetBridgeNamespace()}");
                StartBlock();

                IEnumerable<INamedTypeSymbol> containingTypes = targetSymbol.GetContainingTypes();
                foreach (var containingType in containingTypes.Reverse())
                {
                    AppendLine("/// <summary>");
                    AppendLine("/// 이 브릿지는 다른 라이브러리의 비공개 타입과 멤버에 쉽게 접근할 수 있도록 래핑된 API입니다.<br/>");
                    AppendLine("/// 이 API 사용 시 발생할 수 있는 모든 문제에 대한 책임은 사용자 본인에게 있습니다.<br/>");
                    AppendLine("/// <br/>");
                    AppendLine("/// This bridge is an API wrapper designed to provide easy access to the private types and members of another library.<br/>");
                    AppendLine("/// The user is solely responsible for any issues that may arise from using this API.<br/>");
                    AppendLine("/// <br/>");
                    AppendLine("/// このブリッジは、他のライブラリの非公開タイプやメンバーに簡単にアクセスできるようにラップされたAPIです。<br/>");
                    AppendLine("/// 本APIのご利用により発生する可能性のある全ての問題について、使用者はご自身の責任において対処するものとします。");
                    AppendLine("/// </summary>");
                    if (containingType.IsObsolete(out string message) && SymbolEqualityComparer.Default.Equals(containingType, containingTypes.Last()))
                        AppendLine($"[System.ObsoleteAttribute({message})]");
                    AppendLine(containingType.GetTypeDeclarationText(forceStatic, !SymbolEqualityComparer.Default.Equals(containingType, targetSymbol)));
                    StartBlock();
                }

                switch (targetSymbol.TypeKind)
                {
                    case TypeKind.Class:
                    {
                        ClassBuilder.Build(this, targetSymbol);
                        break;
                    }
                    case TypeKind.Interface:
                    {
                        InterfaceBuilder.Build(this, targetSymbol);
                        break;
                    }
                    case TypeKind.Enum:
                    {
                        EnumBuilder.Build(this, targetSymbol);
                        break;
                    }
                    case TypeKind.Struct:
                    {
                        StructBuilder.Build(this, targetSymbol);
                        break;
                    }
                }

                foreach (var _ in containingTypes)
                    EndBlock();

                EndBlock();
                return builder.ToString();
            }
            catch (Exception e)
            {
                throw new Exception($"{targetSymbol} 타입에서 예외    {e.StackTrace}    {e}");
            }
        }
    }
}