using System.Linq;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using System.Collections.Generic;

namespace RuniOS.APIBridge
{
    /// <summary>
    /// 어셈블리 수준의 GenerateAPIBridgeFor 어트리뷰트를 기반으로 브릿지 코드를 생성하는 소스 생성기입니다.
    /// </summary>
    [Generator]
    public class BridgeGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// 소스 생성기를 초기화하고 코드 생성 로직을 등록합니다.
        /// </summary>
        /// <param name="context">증분 생성기 초기화 컨텍스트입니다.</param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // #1. 생성기에 필요한 사용자 정의 속성을 생성합니다.
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource(
                    "GenerateAPIBridgeForAssemblyAttribute.g.cs",
                    """
                    // <auto-generated/>
                    using System;
                    namespace RuniOS.APIBridge
                    {
                        /// <summary>
                        /// 특정 어셈블리에 대해 재귀적 브릿지 코드 생성을 활성화합니다.
                        /// </summary>
                        /// <param name="targetAssemblies">브릿지 코드를 생성할 대상 어셈블리들의 이름입니다.</param>
                        /// <remarks>
                        /// <para>
                        /// 어셈블리에 이 어트리뷰트가 하나라도 존재하면,<br/>
                        /// 브릿지 코드 생성은 이 어트리뷰트에 명시된 어셈블리로 제한됩니다.
                        /// </para>
                        /// <para>
                        /// 명시되지 않은 어셈블리에 포함된 타입은<br/>
                        /// <see cref="GenerateAPIBridgeForTypeAttribute"/>에 명시되어 있어도 브릿지 코드가 생성되지 않습니다.<br/>
                        /// 또한, 해당 어셈블리 내에서의 재귀적 브릿지 코드 생성도 무시됩니다.
                        /// </para>
                        /// <para>
                        /// 그러나, 명시된 어셈블리의 타입이 명시되지 않은 어셈블리의 비공개 멤버를 참조하는 경우,<br/>
                        /// 해당 비공개 멤버에 대한 브릿지 코드는 여전히 생성됩니다.
                        /// </para>
                        /// <para>
                        /// 이 어트리뷰트가 전혀 지정되지 않은 경우, 모든 어셈블리에 대해 브릿지 코드 생성이 허용됩니다.
                        /// </para>
                        /// </remarks>
                        [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
                        internal sealed partial class GenerateAPIBridgeForAssemblyAttribute(params string[] targetAssemblies) : Attribute
                        {
                            /// <summary>
                            /// 브릿지 코드를 생성할 대상 어셈블리들입니다.
                            /// </summary>
                            public string[] targetAssemblies { get; } = targetAssemblies;
                        }
                    }
                """);

                ctx.AddSource(
                    "GenerateAPIBridgeForTypeAttribute.g.cs",
                    """
                    // <auto-generated/>
                    using System;
                    using System.Reflection;
                    namespace RuniOS.APIBridge
                    {
                        /// <summary>
                        /// 지정된 타입들의 브릿지 코드를 생성하도록 지시합니다.
                        /// </summary>
                        /// <param name="types">브릿지 코드를 생성할 대상 타입들입니다.</param>
                        /// <remarks>
                        /// 이 어트리뷰트는 <see cref="GenerateAPIBridgeForAssemblyAttribute"/>가 지정되지 않았거나, <br/>
                        /// 해당 어트리뷰트에 명시된 어셈블리에 속한 타입에 대해서만 유효합니다.
                        /// </remarks>
                        [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
                        internal sealed partial class GenerateAPIBridgeForTypeAttribute(params Type[] types) : Attribute
                        {
                            /// <summary>
                            /// 브릿지 코드를 생성할 대상 타입들입니다.
                            /// </summary>
                            public Type[] types { get; } = types;
                            
                            /// <summary>
                            /// 포함할 멤버 이름들입니다.<br/>
                            /// 비어있을 경우, 제외된 멤버를 제외한 모두를 포함시킵니다.
                            /// </summary>
                            public string[] includeMember { get; set; } = Array.Empty<string>();
                            
                            /// <summary>
                            /// 제외할 멤버 이름들입니다.
                            /// </summary>
                            public string[] excludeMember { get; set; } = Array.Empty<string>();
                            
                            /// <summary>
                            /// 타겟 타입을 강제로 정적 클래스처럼 처리할지 여부를 설정합니다.
                            /// </summary>
                            public bool forceStatic { get; set; } = false;
                            
                            /// <summary>
                            /// 인스턴스 생성 팩토리(<c>__CreateInstance</c>, <c>__CreateInstanceNonPublic</c>) 메서드의 생성을 건너뛸지 여부를 결정합니다.
                            /// </summary>
                            public bool skipCreateInstance { get; set; } = false;
                        }
                    }
                    """);
            });
            
            // 1. 어셈블리 수준의 GenerateAPIBridgeFor 어트리뷰트를 모두 찾아 모든 타입 인자를 추출합니다.
            var targetTypesProvider = context.CompilationProvider
                .SelectMany(static (compilation, _) =>
                {
                    ImmutableArray<BridgeGenerationData>.Builder generationDataList = ImmutableArray.CreateBuilder<BridgeGenerationData>();
                    var assemblyAttributes = compilation.Assembly.GetAttributes();

                    // GenerateAPIBridgeForAssemblyAttribute 파싱
                    ImmutableArray<string> targetAssemblies = assemblyAttributes
                        .Where(static ad => ad.AttributeClass?.GetFullTypeName() == "global::RuniOS.APIBridge.GenerateAPIBridgeForAssemblyAttribute")
                        .SelectMany(static ad => ad.ConstructorArguments.Where(static ca => ca.Kind == TypedConstantKind.Array))
                        .SelectMany(static ca => ca.Values.Select(static v => (string?)v.Value))
                        .Where(static s => !string.IsNullOrEmpty(s))
                        .OfType<string>()
                        .Distinct()
                        // ReSharper disable once UseCollectionExpression
                        .ToImmutableArray();

                    // GenerateAPIBridgeFor(params Type[] types) 처리
                    foreach (var attributeData in assemblyAttributes.Where(static ad => ad.AttributeClass?.GetFullTypeName() == "global::RuniOS.APIBridge.GenerateAPIBridgeForTypeAttribute"))
                    {
                        // 명명된 인자(includeMember, excludeMember)를 추출합니다.
                        ImmutableArray<string> includeMembers = ImmutableArray<string>.Empty;
                        ImmutableArray<string> excludeMembers = ImmutableArray<string>.Empty;
                        bool forceStatic = false;
                        bool skipCreateInstance = false;

                        // Named arguments 처리
                        foreach (var namedArgument in attributeData.NamedArguments)
                        {
                            switch (namedArgument.Key)
                            {
                                case "includeMember" when namedArgument.Value.Kind == TypedConstantKind.Array:
                                {
                                    // ReSharper disable once UseCollectionExpression
                                    includeMembers = namedArgument.Value.Values.Select(static x => x.Value).OfType<string>().ToImmutableArray();
                                    break;
                                }
                                case "excludeMember" when namedArgument.Value.Kind == TypedConstantKind.Array:
                                {
                                    // ReSharper disable once UseCollectionExpression
                                    excludeMembers = namedArgument.Value.Values.Select(static x => x.Value).OfType<string>().ToImmutableArray();
                                    break;
                                }
                                case "forceStatic" when namedArgument.Value.Kind == TypedConstantKind.Primitive:
                                {
                                    if (namedArgument.Value.Value is bool value)
                                        forceStatic = value;
                                    break;
                                }
                                case "skipCreateInstance" when namedArgument.Value.Kind == TypedConstantKind.Primitive:
                                {
                                    if (namedArgument.Value.Value is bool value)
                                        skipCreateInstance = value;
                                    break;
                                }
                            }
                        }
                        
                        // Positional arguments 처리
                        {
                            if (!attributeData.ConstructorArguments.Any())
                                continue;

                            var positionalArgument = attributeData.ConstructorArguments[0];
                            if (positionalArgument.Kind != TypedConstantKind.Array)
                                continue;

                            foreach (var typeValue in positionalArgument.Values)
                            {
                                if (typeValue.Value is not INamedTypeSymbol typeSymbol)
                                    continue;
                                
                                generationDataList.Add(new BridgeGenerationData(targetAssemblies, typeSymbol.OriginalDefinition, includeMembers, excludeMembers, forceStatic, skipCreateInstance));
                            }
                        }
                    }

                    return generationDataList.ToImmutable();
                }).Collect(); // 모든 결과를 수집합니다.

            // 2. 수집된 모든 타입에 대해 브릿지 코드를 생성합니다.
            context.RegisterSourceOutput(targetTypesProvider, static (SourceProductionContext spc, ImmutableArray<BridgeGenerationData> targetDatas) =>
            {
                // 중복 제거를 위해 GroupBy와 First를 사용하여 DistinctBy와 동일한 기능을 구현합니다.
                IEnumerable<BridgeGenerationData> distinctTargets = targetDatas
                    .GroupBy(static x => x.targetSymbol.OriginalDefinition, SymbolEqualityComparer.Default)
                    .Select(static x => x.First());

                if (!distinctTargets.Any())
                    return;
                
                List<INamedTypeSymbol> bridgedNonPublicTypeSymbols = [];
                List<BridgeGenerationData> nonPublicTypeSymbols = [];
                
                foreach (var targetData in distinctTargets)
                    Build(targetData);
                
                nonPublicTypeSymbols = nonPublicTypeSymbols
                    .Where(x => !bridgedNonPublicTypeSymbols.Contains(x.targetSymbol.OriginalDefinition, SymbolEqualityComparer.Default))
                    .GroupBy(static x => x.targetSymbol.OriginalDefinition, SymbolEqualityComparer.Default)
                    .Select(static x => x.First())
                    .ToList();
                
                {
                    while (nonPublicTypeSymbols.Any())
                    {
                        foreach (BridgeGenerationData data in nonPublicTypeSymbols.ToArray())
                            Build(data);
                        
                        nonPublicTypeSymbols = nonPublicTypeSymbols
                            .Where(x => !bridgedNonPublicTypeSymbols.Contains(x.targetSymbol.OriginalDefinition, SymbolEqualityComparer.Default))
                            .GroupBy(static x => x.targetSymbol.OriginalDefinition, SymbolEqualityComparer.Default)
                            .Select(static x => x.First())
                            .ToList();
                    }
                }
                
                return;

                void Build(BridgeGenerationData targetData)
                {
                    INamedTypeSymbol targetSymbol = targetData.targetSymbol;
                    ImmutableArray<string> includeMembers = targetData.includeMembers;
                    ImmutableArray<string> excludeMembers = targetData.excludeMembers;
                    bool forceStatic = targetData.forceStatic;
                    bool skipCreateInstance = targetData.skipCreateInstance;
                    
                    bridgedNonPublicTypeSymbols.Add(targetSymbol.OriginalDefinition);
                    
                    // targetAssemblies가 지정되었으면 해당 어셈블리에 속하는 타입만 추가
                    if (targetData.targetAssemblies.Any() && !targetData.targetAssemblies.Contains(targetSymbol.ContainingAssembly?.Name ?? string.Empty))
                        return;
                    
                    string fileName = $"{targetSymbol.GetBridgeNamespace()}.{GetBridgeTypeNameIncludeContaining(targetSymbol)}";
                    fileName += ".g.cs";

                    spc.AddSource(fileName, BridgeGeneratorBuilder.Build(targetData.targetAssemblies, targetSymbol, includeMembers, excludeMembers, forceStatic, skipCreateInstance, out IReadOnlyList<BridgeGenerationData> result));
                    nonPublicTypeSymbols.AddRange(result);
                    return;

                    static string GetBridgeTypeNameIncludeContaining(INamedTypeSymbol symbol)
                    {
                        string result = string.Empty;
                        if (symbol.ContainingType != null)
                            result += GetBridgeTypeNameIncludeContaining(symbol.ContainingType) + '.';

                        result += symbol.GetBridgeTypeName();
                        if (symbol.TypeParameters.Any())
                            result += "`" + symbol.TypeParameters.Length;
                        
                        return result;
                    }
                }
            });
        }
    }
}
